version: "3"

services:
  primary-sql:
    env_file:
      - .env
    container_name: main-sql
    image: mysql
    build:
      context: ./docker/mysql
    environment:
      MYSQL_DATABASE: ${PRIMARY_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${PRIMARY_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${PRIMARY_MYSQL_USER}
      MYSQL_PASSWORD: ${PRIMARY_MYSQL_PASSWORD}
    ports:
      - ${PRIMARY_MYSQL_PORT}:3306
    volumes:
      - ./docker/mysql/primary/my.conf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/primary/logs:/var/log/mysql:rw
      - ./docker/mysql/dumps:/var/log/dumps:rw
      - main:/var/lib/mysql
    depends_on:
      - replica-sql-1
      - replica-sql-2

  replica-sql-1:
    env_file:
      - .env
    container_name: replica-sql-1
    image: mysql
    build:
      context: ./docker/mysql
    environment:
      MYSQL_DATABASE: ${REPLICA_1_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${REPLICA_1_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${REPLICA_1_MYSQL_USER}
      MYSQL_PASSWORD: ${REPLICA_1_MYSQL_PASSWORD}
    ports:
      - ${REPLICA_1_MYSQL_PORT}:3306
    volumes:
      - ./docker/mysql/replica-1/my.conf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/replica-1/logs:/var/log/mysql:rw
      - ./docker/mysql/dumps:/var/log/dumps:rw
      - replication-1:/var/lib/mysql

  replica-sql-2:
    env_file:
      - .env
    container_name: replica-sql-2
    image: mysql
    build:
      context: ./docker/mysql
    environment:
      MYSQL_DATABASE: ${REPLICA_2_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${REPLICA_2_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${REPLICA_2_MYSQL_USER}
      MYSQL_PASSWORD: ${REPLICA_2_MYSQL_PASSWORD}
    ports:
      - ${REPLICA_2_MYSQL_PORT}:3306
    volumes:
      - ./docker/mysql/replica-2/my.conf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/replica-2/logs:/var/log/mysql:rw
      - ./docker/mysql/dumps:/var/log/dumps:rw
      - replication-2:/var/lib/mysql


volumes:
  main:
  replication-1:
  replication-2:
